apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-web
  namespace: harness-gitops
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: dev
            server: https://kubernetes.default.svc
          - env: prod
            server: https://kubernetes.default.svc.cluster.local
  template:
    metadata:
      name: "hello-web-{{.env}}"
      labels:
        harness.io/serviceRef: hello_web
        harness.io/envRef: "{{.env}}"
    spec:
      project: default-gitops-demo
      source:
        repoURL: https://github.com/iHyunWoo/harness-gitops-demo.git
        path: apps/hello-web/chart
        targetRevision: main
        helm:
          valueFiles:
            - "../envs/{{.env}}/values.yaml"
      destination:
        server: "{{.server}}"
        namespace: "hello-{{.env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
